# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-zhubonan-github-io'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'About me',   url: 'about.html'}
- {name: 'Posts', url: 'posts.html'}
- {name: 'Codes', url: 'codes.html'}
- {name: 'Publications', url: 'publications.html'}
- {name: 'Contact', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github',     link: 'https://www.github.com/zhubonan'}
- {icon: 'twitter',    link: 'https://twitter.com/1stbz'}
#- {icon: 'linkedin',   link: 'http://www.linkedin.com/in/lenpaul/'}
#- {icon: 'envelope',   link: 'mailto:l.nguyen.paul@gmail.com'}
- {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

github_url: https://www.github.com/zhubonan

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'

software_urls:
  castep: http://www.castep.org
  vasp: https://vasp.at
  aiida: https://aiida.net
